name: CIDocker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Needed File
      run: |
        touch password.env

    - name: Build and push
      uses: docker/bake-action@v6
      with:
        push: false
        print: true
        set: |
          *.platform=linux/amd64,linux/arm64
        
